### ISSUE TITLE
Issue executing Numspy 

### ISSUE THREAD

**Issue by harry0987** [bhattsameer/numspy#1]
Hi Sameer,
I was trying to execute your code  with python 3.6 and got the following error:
[97m[~] [0m[97mProcessing...[0m
[32m[+] [0m[92mSuccessfully logged in.[0m
[33m[!] [0m[97mVerifying sent message...[0m
Traceback (most recent call last):
  File "F:\SB_Scripts\Docs_Ref\30_08_2018\numspy-master\Examples\numspy_example.py", line 13, in <module>
    w2s.send(mobile_number,"hello numspy testing")
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\numspy\__init__.py", line 80, in send
    if self._sent_verify(to_number, message):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\numspy\__init__.py", line 108, in _sent_verify
    _mobile = str(first.find('b').text)
AttributeError: 'NoneType' object has no attribute 'find'
>>> 

Please guide how to fix this error so that NumSpy can be used error free. 

Thanks
Harry

**Comment by bhattsameer** [comment]
Hi Harry,
Yes because of this module is developed using previous website of  Way2sms, which is fully updated by way2sms so this module no more working, I will update the code as per new website of Way2sms soon.

Thanks.

**Comment by harry0987** [comment]
Hi Sameer,
Thanks for your support and prompt response. Looking forward for the updated code.

Thanks
Harry

**Comment by bhattsameer** [comment]
Hi Harry,
Welcome and ya if you in hurry and wants to get thing fast you can update some things by yourself too.
you can download source package from https://pypi.org/project/numspy/ hope this will help you out.

I will update the code soon.

Thanks and happy coding.

**Comment by harry0987** [comment]
Hi Sameer,


Thanks
Harry

**Comment by harry0987** [comment]
Hi Sameer,
I downloaded the code and tried fixing the bugs but facing some issues. I am not in a hurry. Will check for code updates from your side.

Thanks
Harry
